server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/