server:
  port: 8088
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/api/v1/users/**
        - id: mortgageLoanService
          uri: lb://mortgageLoanService
          predicates:
            - Path=/api/v1/mortgageloan/**
            