server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MortgageLoanServiceDB
    username: postgres
    password: Silvestre9+
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/