server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserServiceDB
    username: postgres
    password: Silvestre9+
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/