apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluationservice-deployment
  labels:
    app: evaluationservice-deployment
spec:
  selector:
    matchLabels:
      app: evaluationservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: evaluationservice-deployment
    spec:
      containers:
        - name: evaluationservice
          image: sof1215/evaluationservice:latest
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"