apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluationService-deployment
  labels:
    app: evaluationService-deployment
spec:
  selector:
    matchLabels:
      app: evaluationService-deployment
  replicas: 1
  template:
    metadata:
    labels:
      app: evaluationService-deployment
    spec:
      containers:
      - name: user-service
        image: sof1215/evaluationservice:latest
        ports:
          - containerPort: 8093
        env:
          - name: SERVER_PORT
            value: "0"