--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: MortgageLoanServiceDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "MortgageLoanServiceDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Chile.1252';


ALTER DATABASE "MortgageLoanServiceDB" OWNER TO postgres;

\connect "MortgageLoanServiceDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: mortgageloanentity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mortgageloanentity (
    id bigint NOT NULL,
    maxamount real,
    maxinterestrate real,
    maxterm integer,
    mininterestrate real,
    type integer
);


ALTER TABLE public.mortgageloanentity OWNER TO postgres;

--
-- Name: mortgageloanentity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mortgageloanentity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mortgageloanentity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: mortgageloanentity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mortgageloanentity (id, maxamount, maxinterestrate, maxterm, mininterestrate, type) FROM stdin;
1	0.8	0.05	30	0.035	1
2	0.7	0.06	20	0.04	2
3	0.6	0.07	25	0.05	3
4	0.5	0.06	15	0.045	4
\.


--
-- Name: mortgageloanentity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mortgageloanentity_id_seq', 4, true);


--
-- Name: mortgageloanentity mortgageloanentity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mortgageloanentity
    ADD CONSTRAINT mortgageloanentity_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

