apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_USERS: postgres-service
  DB_PORT_USERS: "5432"
  DB_DBNAME_USERS: usersdb
  