apiVersion: apps/v1
kind: Deployment
metadata:
  name: userService-deployment
  labels:
    app: userService-deployment
spec:
  selector:
    matchLabels:
      app: userService-deployment
  replicas: 1
  template:
    metadata:
    labels:
      app: userService-deployment
    spec:
      containers:
      - name: user-service
        image: sof1215/user-service:latest
        ports:
          - containerPort: 8090
        env:
          - name: SERVER_PORT
            value: "8090"
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config-map
                key: DB_PORT_USERS