--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: user-db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "user-db" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Chile.1252';


ALTER DATABASE "user-db" OWNER TO postgres;

\connect "user-db"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: userentity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.userentity (
    id bigint NOT NULL,
    birthdate timestamp(6) without time zone,
    email character varying(255),
    name character varying(255),
    rut character varying(255),
    salary integer NOT NULL
);


ALTER TABLE public.userentity OWNER TO postgres;

--
-- Name: user_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.userentity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: userentity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.userentity (id, birthdate, email, name, rut, salary) FROM stdin;
2	2002-12-11 21:00:00	andreaFuentes@gmail.com	Andrea Fuentes	33444555-6	800000
3	1999-07-07 20:00:00	sebastianG@gmail.com	Sebastian Gallardo	12444555-7	900000
4	2001-12-11 21:00:00	juanRojas@gmail.com	Juan Rojas	6123987-K	0
9	2000-12-11 21:00:00	sandraPalacios@gmail.com	Sandra Palacios	12333777-3	1000000
11	2000-06-10 20:00:00	javierC@gmail.com	Javier Campos	13333777-K	1000000
12	1999-01-11 21:00:00	alejandroCuevas@gmail.com	Alejandro Cuevas	19087654-K	0
13	1987-07-11 20:00:00	camilaLagos@gmail.com	Camila Lagos	13567890-0	0
14	1976-07-07 20:00:00	sebaAguilar@gmail.com	Sebastian Aguilar	14567123-1	0
15	1967-11-07 20:00:00	gabrielaS@gmail.com	Gabriela Sanchez	7890123-3	0
16	1959-12-08 20:00:00	juanR@gmail.com	Juan Rodriguez	5345678-2	0
17	1986-09-14 20:00:00	soniaInostroza@gmail.com	Sonia Inostroza	18098765-6	0
18	1982-01-11 21:00:00	samuelGarcia@gmail.com	Samuel Garcia	22146345-K	0
19	1984-08-06 20:00:00	camiloRios@gmail.com	Camilo Rios	17098765-3	0
20	1979-02-16 21:00:00	matiasLazo@gmail.com	Matias Lazo	15678123-5	0
21	1958-05-13 20:00:00	gabrielS@gmail.com	Gabriel Santibañez	6123987-6	0
22	1965-03-18 20:00:00	valentinR@gmail.com	Valentin Rojas	7456765-3	0
23	1988-04-20 20:00:00	pedroMartinez@gmail.com	Pedro Martinez	15678123-6	0
\.


--
-- Name: user_entity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_entity_id_seq', 23, true);


--
-- Name: userentity user_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userentity
    ADD CONSTRAINT user_entity_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

