apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice-deployment
spec:
  selector:
    matchLabels:
      app: userservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice-deployment
    spec:
      containers:
        - name: userservice
          image: sof1215/userservice:latest
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_USERS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_USERS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_USERS
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_USER_USERS
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PASSWORD_USERS